### ISSUE TITLE
issue with launching AnimalTA

### ISSUE THREAD

**Issue by asalin0** [VioletteChiara/AnimalTA#10]
Dear Violette,

I wanted to install and try animalTA to evaluate whether it fits with my video analysis needs.

However, after the installation, I am not able to create a new project properly.
After clicking on the "new project" button and selecting in which folder I want to save it, it looks like nothing happen in the main window even though in the information window the following text appears "Click <Add video(s)> button to add video(s) to your project (...)"

Have you ever had such issue ? 

Thanks for your help,

Adélie

**Comment by VioletteChiara** [comment]
Dear Adélie,

Thank you very much for reaching out.
I never got any report of a similar issue. Are you under Windows OS?

Regards,

Violette

**Comment by asalin0** [comment]
I am :)

**Comment by VioletteChiara** [comment]
In that case, you should be able to see the <Add video> button in the top left corner.
![image](https://github.com/VioletteChiara/AnimalTA/assets/78436110/66fec13e-23c2-47df-abf9-c513949862e6)

If this button is not available, do you see the name of your project here:
![image](https://github.com/VioletteChiara/AnimalTA/assets/78436110/a9649d00-1108-4fb3-95f7-2c2de9f4e948)

**Comment by VioletteChiara** [comment]
Thanks for this information, it allowed me to determine in which part of the code the problem was occurring. 
Unfortunately, I was not able to reproduce the bug. 
Would you agree to download and install this debugging version of the program (http://vchiara.eu/AnimalTA%20installer%20debugging.exe), and copy-paste me here the output messages it gives you when you create a new project?

**Comment by asalin0** [comment]
Sure !

Here the output messages : 

![image](https://github.com/VioletteChiara/AnimalTA/assets/141122868/87100746-f3e7-4aba-baff-685c4136c72b)
![image](https://github.com/VioletteChiara/AnimalTA/assets/141122868/4b4479a4-accb-4033-9236-bab6a617d8b6)
![image](https://github.com/VioletteChiara/AnimalTA/assets/141122868/69df109c-4a60-4557-995c-377f60e002ea)

**Comment by VioletteChiara** [comment]
Hi! Sorry for the delay in my answer, and thanks a lot for your help.

It seems that for some unknown reasons, the program installation did not work correctly, and some files appear to be missing.
I believe you can fix this issue by downloading the files in this repository: https://github.com/VioletteChiara/AnimalTA/tree/master/AnimalTA/Files
(you can use this link to directly download all of them: http://vchiara.eu/Files.zip ).

Then unzip/paste those Files in this location (just adapt to your computer): C:\Users\User\AppData\Local\Programs\AnimalTA\AnimalTA\Files

 (If it is not there, you kind find the path toward the program files using the installer, the path will be displayed).

You should have this structure:
--> Programs
  --> AnimalTA
    --> AnimalTA
      --> Files
         --> Alert.mp3
         --> Concat.png
         --> ....

**Comment by asalin0** [comment]
Hi Violette !

I downloaded the files sent and unzipped it in the precised location (see below). However I still have the same message of error and I am not able to see the button to upload a video.

![image](https://github.com/VioletteChiara/AnimalTA/assets/141122868/9c64cb9f-7e60-4a5e-a830-e65db8ce8517)

![image](https://github.com/VioletteChiara/AnimalTA/assets/141122868/c229d5dc-459c-4cdf-a0ed-164fe53be653)


Thanks for your time on this issue !!

**Comment by Ruben3005** [comment]
Hi, I have exactly the same problem asalin0 mentions. Please let us know about any new developments or possible solutions. I run the program on Windows 11.
Greetings

**Comment by Ruben3005** [comment]
Problem solved:
For some reason when installing in the "user" folder an error occurs that does not allow the software to work correctly, I was able to solve it by choosing the "C:" drive as the destination folder outside the user for the installation of the program. "C:\ProgramData\AnimalTA" is the destination folder I used for the installation and it has worked fine ever since.

Greetings, I hope my experience is useful to you.

**Comment by VioletteChiara** [comment]
Hello!

Sorry for not answering earlier, I was still trying to fond a solution, but couldn't reproduce the problem.  

Thank you very much for this solution Ruben3005.!

Now that you have identified where the problem was coming from, I can reproduce it and I will try making a fix for the next update. In the meantime your solution is great :)

**Comment by asalin0** [comment]
With your solution Ruben3005 it works perfectly fine.

Thank you both !
