### ISSUE TITLE
Tracking data not share common axis

### ISSUE THREAD

**Issue by Fusenheizi** [VioletteChiara/AnimalTA#12]
Hi Violette,

I encountered an issue while plotting tracking data; I found that different videos use different coordinate reference systems. In other words, different videos do not share a common origin point for the coordinate axis. 

Specifically, what I have done is to crop multiple segments from one video and then using the same parameters for analysis, where the environment and shape remain unchanged.

Is it possible to add corresponding settings so that we can use the same axis for different videos when applying the same parameters?

Jay Lin

**Comment by VioletteChiara** [comment]
Dear Jay Lin,

The video's coordinates origin point is always the top left corner of the video (after cropping). 

When you say that you cropped multiple segments, do you mean that you copied the same video several times and cropped it (X / Y cropping) differently for each copy? If so, the point of origin will indeed be modified. 

However, I believe such a problem may be fixed by separating your video in arenas instead of separating using the cropping option. In case of separation with arenas, the origin of the axis will remain the same (top left corner of the video). It will also avoid making multiple copies of the same video. 

Best regards,

Violette
